### ISSUE TITLE
mode changes in the 1.5 patch

### ISSUE THREAD

**Issue by dvirtz** [Xilinx/video-sdk#11]
Most of the 1.5 [patch](https://github.com/Xilinx/video-sdk/blob/master/sources/app-ffmpeg4-xma-patch/0001-Add-plugins-to-support-U30-based-Video-SDK-v1.5.0.patch) is just mode changes. Seems like someone did `chmod +x -R .' before committing:
```
 mode change 100644 => 100755 .gitattributes
 mode change 100644 => 100755 .gitignore
 mode change 100644 => 100755 .travis.yml
 mode change 100644 => 100755 CONTRIBUTING.md
 mode change 100644 => 100755 COPYING.GPLv2
```
etc.

**Comment by jmouroux** [comment]
@dvirtz  Yes, this is true and unnecessary.  We'll be working on an updated patch to remove these chmod modifications.
