### ISSUE TITLE
XRT submodule tag is incorrect

### ISSUE THREAD

**Issue by rnertney** [Xilinx/video-sdk#14]
XRT submodule refs 2.10.0, building xvbm requires 2.10.37 or later.

**Comment by ThomasXilinx** [comment]
The XRT submodule for v1.5 correctly points to the XRT tag for v1.5:
https://github.com/Xilinx/xrt/tree/244440c52fdc373a80a17f5b54d751648f69b9ec
https://github.com/Xilinx/XRT/releases/tag/u30_ga_1.5

After cloning the repo, if you run "git submodule update --init --recursive", you will the following confirmation at the end:
Submodule path 'sources/xrt': checked out '244440c52fdc373a80a17f5b54d751648f69b9ec'
