### ISSUE TITLE
Shebang shoud be top of a file

### ISSUE THREAD

**Issue by anjn** [Xilinx/video-sdk#27]
Some scripts will not work as expected in Ubuntu since the default shell of Ubuntu is `/bin/dash` and a shebang `#!/bin/bash`  is not at the top of the files. For example, [the latency_test](https://github.com/Xilinx/video-sdk/blob/v1.5/examples/ffmpeg/quality_analysis/latency_test.sh) script doen't work in Ubuntu.

**Comment by ThomasXilinx** [comment]
Thanks for reporting the issue. We will provide updated version of the scripts shortly.
