### ISSUE TITLE
Scaling unsupported AVC profile efficiently

### ISSUE THREAD

**Issue by ghost** [Xilinx/video-sdk#29]
This is a followup on  #28 

My original chunk is has an unsupported AVC profile (constrained baseline) and is 60fps full hd. How do I use hw efficiently in order to transcode it to a 1920x720 (same fps) ? Will this command do:
```
ffmpeg -i originalChunk.ts -filter_complex "multiscale_xma=outputs=1: out_1_width=1280: out_1_height=720: out_1_rate=full: [a]" -map "[a]" -b:v 1000K  -c:v mpsoc_vcu_h264 -y transcodedChunk.ts
```

**Comment by ThomasXilinx** [comment]
Yes, this will do. With this command, the decoding will be done in SW, then the scaling and the encoding will be done using the HW accelerators.
