### ISSUE TITLE
U30 Ubuntu 18.04 install failed

### ISSUE THREAD

**Issue by amrragab8080** [Xilinx/video-sdk#3]
==> amazon-ebs: + cd video-sdk/release/U30_Ubuntu_18.04_v1.5_20210827
==> amazon-ebs: + sh install.sh
==> amazon-ebs: install.sh: 34: install.sh: Syntax error: Bad function name

https://github.com/Xilinx/video-sdk/blob/master/release/U30_Ubuntu_18.04_v1.5_20210827/install.sh#L34

AWS EC2 vt1.3xlarge - UL18.04.5

**Comment by ThomasXilinx** [comment]
Hi Amr, can you provide more details on exact sequence of steps that you are following and the context that you are in?

**Comment by jmouroux** [comment]
@amrragab8080  Please run as $ ./install.sh   The shell script uses bash syntax (not sh).  The extension is misleading.

**Comment by amrragab8080** [comment]
changing to `bash install.sh`  works for the packer build
