### ISSUE TITLE
Can't exec ffmpeg from nginx rtmp exec 

### ISSUE THREAD

**Issue by moerradi** [Xilinx/video-sdk#30]
I am using nginx rtmp as my media server, I use the exec directive to execute ffmpeg and transcode the input stream to multiple qualities using abr, after testing abr with live videos and mp4 videos and it seeming to work i tried integrating it in nginx rtmp exec and it gives out the following : 
```
/opt/xilinx/ffmpeg/bin/ffmpeg: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory
``` 
the problem is that I don't source the /opt/xilinx/xcdr/setup.sh file inside the script but sourcing it every time will create a huge 2 seconds delay, is there a solution to this ?
Is there a way i can permanently source the file or something like that ?

**Comment by ThomasXilinx** [comment]
The delay associated with sourcing setup.sh will be improved in the next release of the SDK.

In the meantime, you should be able to use a modified version of the script in your exec command. The setup.sh script does two main things: #1 setting up runtime environment variables; #2 initialize the devices and the resource manager (XRM). #2 only needs to be done once. So you could create a version of the setup.sh script which only sets up the needed environment variables and use that script with the exec directive.

**Comment by moerradi** [comment]
I think this solves the issue, I copied only the env setting part of the script and added it in the beginning of my scripts and it works like a charm !
Thank you very much
