### ISSUE TITLE
[AWS EKS] Kubernetes compatible AMIs past v1.19

### ISSUE THREAD

**Issue by LewisJackson1** [Xilinx/video-sdk#38]
I'm currently using `ami-0af44f81c3e6a68ac` with the name of `al2-xilinx-vt-ga1.5-eks-ami-4.14-3b50633b-1f1b-4c14-b26b-cb33681d076f` and description `al2-xilinx-vt-fsx-processor_eks-1.19-1633454662` on an EKS cluster in a separate managed NodePool. This image is for Kubernetes v1.19, and I'd like to upgrade my cluster past that version but I can't with an old NodePool version.

How can I pull in upgrades to the Kubernetes version?

**Comment by yuzhang66** [comment]
Hi Lewis,

Is your cluster currently using a mismatched version of EKS version other than 1.19?
If so, You can try remove the VT1 NodeGroup first, upgrade the cluster and then let VT1 NodeGroup rejoin the cluster.

Thanks,
--Yu

**Comment by LewisJackson1** [comment]
Hi Yu!

> Is your cluster currently using a mismatched version of EKS version other than 1.19?

This is correct, yes.

> If so, You can try remove the VT1 NodeGroup first, upgrade the cluster and then let VT1 NodeGroup rejoin the cluster.

That's a good workaround if we really need it, thanks. However, this wouldn't be ideal as we have production workloads running on the NodeGroup. Are Xilinx not aiming to provide upgraded versions?

**Comment by yuzhang66** [comment]
Hi Lewis,

This is an limitation from the AWS EKS, user can not use the EKS auto upgrade function while using mismatched version of EKS. If your cluster and NodeGroup use the matched version of EKS, I believe you will be able to upgrade them all together.

We will provide AMI with newer EKS version in future releases, for each AMI release, we need to pass through the legal approval of all the packages used inside this AMI, so we can not always catch up with the latest EKS version release.

Another option is you can reference following links to build your own EKS AMI and customized it:
EKS Base AMI building: [https://github.com/awslabs/amazon-eks-ami](https://github.com/awslabs/amazon-eks-ami)
EKS VT AMI building (based on the eks base ami): [https://github.com/awslabs/amazon-eks-ami](https://github.com/aws-samples/aws-vt-baseami-pipeline)

I'm also dig into the EKS document to see if there's a possible way for user to manually upgrade the EKS package inside the worker node, will let you know if I have any update about it.

Thank you,
--Yu

**Comment by LewisJackson1** [comment]
Ah okay, I think I'll try to create my own image going forward then. Thanks for the advice 👍🏻

**Comment by NastoohX** [comment]
As there are no further issues closing this.
