### ISSUE TITLE
Error in memory report

### ISSUE THREAD

**Issue by mutagenspree** [Xilinx/video-sdk#39]
I use video-sdk on vt1 machine at AWS
When I run xbutil examine --device <BDF> -r memory -f json -o mem_report.json I see error message in json file:
`"error_msg": "Failed to find subdirectory for DDR[0] under \/sys\/bus\/pci\/devices\/0000:00:1f.0\n"`

And I can see it only in json report. Nothing in STDOUT or logs

Should I worry about it?

**Comment by NastoohX** [comment]
Hi,
--device requires an argument in BDF format. As an example, these are the devices on my setup:

```
Devices present
  [0000:e3:00.1] : xilinx_u30_gen3x4_base_2 
  [0000:e2:00.1] : xilinx_u30_gen3x4_base_2 
  [0000:22:00.1] : xilinx_u30_gen3x4_base_2 
  [0000:21:00.1] : xilinx_u30_gen3x4_base_2
```

And to get memory info on the 1st device, the following command is issued:

```
xbutil examine --device 0000:e3:00.1 -r memory -f json -o mem_report.json

----------------------------------------------
1/1 [0000:e3:00.1] : xilinx_u30_gen3x4_base_2
----------------------------------------------
Memory Information

  Memory Topology
         Tag         Type        Temp(C)  Size      Base Address    
    [ 0] DDR[0]      MEM_DRAM    N/A      1023 MB   0x800000000     

  Memory Status
         Tag         Type        Size    Mem Usage       BO count
    [ 0] DDR[0]      MEM_DRAM    2 GB    65180 KB        42      

  Soft Kernel Memory Status
    HostBO Count      MapBO Count     UnmapBO Count   FreeBO Count    
    0                 0               0               1073725440  
...

```

Hope this helps.
Cheers,

**Comment by NastoohX** [comment]
Hi,
This is not an error message, but rather an informative one stating that /sys/bus/pci/devices/0000:00:1f.0/DDR[0] does not exists, which is expected.
Cheers,
