### ISSUE TITLE
Hardware accelerated decoding fails on M1 macs for certain videos encoded with h264

### ISSUE THREAD

**Issue by Mudpuppy12** [Xilinx/video-sdk#43]
Playback on an M1 mac says video file corruption on a browser playback.

We have tracked down the issue which is similar below

https://trac.ffmpeg.org/ticket/9713
https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=c534d9f72a89542ed639071b1ae15893aadf1f18

This bug also seems to be affecting the xlinux codec as well.

**Comment by NastoohX** [comment]
Hi,
Thank you for bringing this issue and its solution to our attention! I'll inform our dev team of your findings.
Thanks again.
Cheers,

**Comment by Mudpuppy12** [comment]
Why was this issue closed? We are still seeing problems with this.

**Comment by NastoohX** [comment]
Hi,
Thank you for the followup. As the problem is currently stated, it is either specific to M1 or version 4.4 of FFmpeg which our release is based on. We can't do much for the 1st case; however, we will revisit this problem, when we have updated our base FFmpeg.
Cheers,
