### ISSUE TITLE
u30 failed to load xclbins 

### ISSUE THREAD

**Issue by MarcusWay45** [Xilinx/video-sdk#45]
**result after running** : `source /opt/xilinx/xcdr/setup.sh`
{
    "response": {
        "name": "load",
        "requestId": "1",
        "status": "failed",
        "data": {
            "failed": "xclLoadXclBin failed, rc = -22, failed to load /opt/xilinx/xcdr/xclbins/transcode.xclbin to device 0"
        }
    }
}
-----Load xrm plugins-----
{
    "response": {
        "name": "loadXrmPlugins",
        "requestId": "1",
        "status": "failed",
        "data": {
            "failed": "plugin xrmU30DecPlugin (version 2) is already loaded"
        }
    }
}

**Comment by NastoohX** [comment]
Hi MarcusWay45,
Thank you for bringing this matter to our attention. For debugging purposes, could you, kindly, provide the following information:

1- Which version of video sdk is this instance running?
2- Is this an AWS instance?
3- What distro and kernel version is this instance running on, e.g., output of the following commands?

  `lsb_release`
  `uname -ar`

4- What is the output of the following commands?
  `source /opt/xilinx/xrt/setup.sh`
 `xbutil examine`

5- What is the full output of `source /opt/xilinx/xcdr/setup.sh` command?

Cheers,

**Comment by MarcusWay45** [comment]
> Hi MarcusWay45, Thank you for bringing this matter to our attention. For debugging purposes, could you, kindly, provide the following information:
> 
> 1- Which version of video sdk is this instance running? 2- Is this an AWS instance? 3- What distro and kernel version is this instance running on, e.g., output of the following commands?
> 
> `lsb_release` `uname -ar`
> 
> 4- What is the output of the following commands? `source /opt/xilinx/xrt/setup.sh` `xbutil examine`
> 
> 5- What is the full output of `source /opt/xilinx/xcdr/setup.sh` command?
> 
> Cheers,

Thank you for your kindly response I'm sorry about not to mention about OS or Hardware 
1) I'm running Video-SDK 2.0 
2) I'm using 2 Cards of Alveo U30 with already set up and config following by the manual 
3)  `uname -ar` _Linux bva-Super-Server 4.15.0-193-generic #204-Ubuntu SMP Fri Aug 26 19:20:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux_
4) `source /opt/xilinx/xrt/setup.sh`
XILINX_XRT        : /opt/xilinx/xrt
PATH              : /opt/xilinx/xrt/bin:/home/bva/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH   : /opt/xilinx/xrt/lib:
PYTHONPATH        : /opt/xilinx/xrt/python:
`xbutil examine`
_System Configuration
  OS Name              : Linux
  Release              : 4.15.0-193-generic
  Version              : #204-Ubuntu SMP Fri Aug 26 19:20:21 UTC 2022
  Machine              : x86_64
  CPU Cores            : 32
  Memory               : 128855 MB
  Distribution         : Ubuntu 18.04 LTS
  GLIBC                : 2.27
  Model                : Super Server

XRT
  Version              : 2.12.427
  Branch               : 2021.2
  Hash                 : 2719b6027e185000fc49783171631db03fc0ef79
  Hash Date            : 2021-10-08 22:10:57
  XOCL                 : 2.12.427, 2719b6027e185000fc49783171631db03fc0ef79
  XCLMGMT              : 2.12.427, 2719b6027e185000fc49783171631db03fc0ef79

Devices present
  [0000:c1:00.1] : xilinx_u50lv_gen3x4_xdma_base_2 user(inst=128)
  [0000:81:00.1] : xilinx_u50lv_gen3x4_xdma_base_2 user(inst=129)
  [0000:45:00.1] : xilinx_u30_gen3x4_base_2 user(inst=134)
  [0000:44:00.1] : xilinx_u30_gen3x4_base_2 user(inst=133)
  [0000:43:00.1] : xilinx_u30_gen3x4_base_2 user(inst=132)
  [0000:42:00.1] : xilinx_u30_gen3x4_base_2 user(inst=131)
  [0000:01:00.1] : xilinx_u50lv_gen3x4_xdma_base_2 user(inst=130)_

5) `source /opt/xilinx/xcdr/setup.sh`
_---------------------------------------
-----Source Xilinx U30 setup files-----
XILINX_XRT        : /opt/xilinx/xrt
PATH              : /opt/xilinx/xrt/bin:/opt/xilinx/xrt/bin:/home/bva/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH   : /opt/xilinx/xrt/lib:/opt/xilinx/xrt/lib:
PYTHONPATH        : /opt/xilinx/xrt/python:/opt/xilinx/xrt/python:
XILINX_XRM      : /opt/xilinx/xrm
PATH            : /opt/xilinx/xrm/bin:/opt/xilinx/xrt/bin:/opt/xilinx/xrt/bin:/home/bva/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH : /opt/xilinx/xrm/lib:/opt/xilinx/xrt/lib:/opt/xilinx/xrt/lib:
xrmd is already active and running
Number of U30 devices found : 4
{
    "response": {
        "name": "load",
        "requestId": "1",
        "status": "failed",
        "data": {
            "failed": "xclLoadXclBin failed, rc = -22, failed to load /opt/xilinx/xcdr/xclbins/transcode.xclbin to device 0"
        }
    }
}
-----Load xrm plugins-----
{
    "response": {
        "name": "loadXrmPlugins",
        "requestId": "1",
        "status": "ok"
    }
}
---------------------------------------_

**Comment by NastoohX** [comment]
Thank you for the info. The problem is due to incompatible version of XRT, i.e, 2.12.427, wrt video sdk 2.0, which requires version 2.11.691. (Kindly, note that we do not support mixed card environment.) To properly enable video sdk 2.0, you need to:
1- `sudo apt purge xrt`
2- Rerun install script, as per https://xilinx.github.io/video-sdk/v2.0/getting_started_on_prem.html#install-the-sdk
3- Reboot the chassis
Let us know if this resolves your issue.
Cheers,

**Comment by MarcusWay45** [comment]
> Thank you for the info. The problem is due to incompatible version of XRT, i.e, 2.12.427, wrt video sdk 2.0, which requires version 2.11.691. (Kindly, note that we do not support mixed card environment.) To properly enable video sdk 2.0, you need to:
> 1- `sudo apt purge xrt`
> 2- Rerun install script, as per https://xilinx.github.io/video-sdk/v2.0/getting_started_on_prem.html#install-the-sdk
> 3- Reboot the chassis
> Let us know if this resolves your issue.
> Cheers,

Thank you,Will follow your instructions 
Peace

**Comment by MarcusWay45** [comment]
Want to update about your instructions
 I Following  in this link https://xilinx.github.io/video-sdk/v2.0/getting_started_on_prem.html#install-the-sdk 
After Cold Boot Step My Machine ran into terminal mode when it boot you know how to fix it ?

**Comment by MarcusWay45** [comment]
Could you explain me , How to deal with mixed card environment that you said

**Comment by NastoohX** [comment]
Hi,
It very much depends on whether the other card(s) within your chassis is able to work with XRT version 2.11.691 or not. If so, we do not foresee any problems. (You will need to check the specific requirements wrt the other card(s).) If this is not the case and other card(s) do not need to directly interact with U30, then an alternative _could_ be to run multiple VMs on the host, where each card is mapped to a single VM, with the correct version of XRT.  It should be noted that we have not tested this option.
Cheers,
