### ISSUE TITLE
AV1 support on Alveo U30

### ISSUE THREAD

**Issue by krlc** [Xilinx/video-sdk#46]
I was wondering if it is possible for U30 to support AV1 transcoding and if so, are there any plans? If I understand correctly, though, currently an h264/h265 transcoding happens on dedicated cores on Zynq and not in FPGA part, so were there any tests to see if FPGA implementation of AV1 transcoding yields meaningful performance? We are thinking on starting to support AV1, but so far the best solution is to use Intel ARC GPUs.

P.S. Sorry if it’s not an appropriate place for this question.

**Comment by NastoohX** [comment]
Hi,

Thank you for your inquiry. U30 does not support AV1 decoding or encoding. For other and upcoming products, kindly, forward your questions to Video-SDK@amd.com.

Cheers,
