### ISSUE TITLE
example ffmpeg FTRT "split and stitch" script doesn't reach full U30 performance

### ISSUE THREAD

**Issue by leifrein** [Xilinx/video-sdk#5]
The script provided here:
https://xilinx.github.io/video-sdk/v1.5/examples/ffmpeg/tutorials.html#ftrt-across-multiple-xilinx-devices-for-maximum-fps

as well as in the cloned repo here:
video-sdk/examples/ffmpeg/tutorials/13_ffmpeg_transcode_only_split_stitch.py

doesn't reach full performance for file based inputs. Specifically it places just just 1 clip segment per transcode device, when we'd expect it to place 4x segments per device for 60fps and 8x for 30fps.

**Comment by ThomasXilinx** [comment]
The script measures efficiency as follows: <clip duration> / ( <time from start to completion> * <number of segments>)

In your example: 2156 sec / (45 sec x 64 ) = 74.86%

The only way you can get 100% is if <time from start to completion> is equal to <clip duration> / <number of segments>. The time it takes to transcode each segment will be in that range. But <time from start to completion> also includes the time it takes to split the input clip and the time it takes to stitch the results back after the transcoding. This is why the efficiency (as calculated by the script) cannot be 100%.
