### ISSUE TITLE
retain inputs EIA-608/EIA-708 and ID3 timed text data using mpsoc_vcu_h264

### ISSUE THREAD

**Issue by scottf-tvw** [Xilinx/video-sdk#54]
as referenced in issue #53, how would you retain and pass (map) both EIA-608/EIA-708 and ID3 data using mpsoc_vcu_h264 decoder/scaler/encoder if it exists in the source input stream? (using ffmpeg)
I have tried many options and failed to retain this data in the hls segments.

**Comment by NastoohX** [comment]
Hi,
As noted in https://github.com/Xilinx/video-sdk/issues/53, we do not retain those SEI elements during transcode operation.  Depending on your flow, you may be able to extract the existing CC and reinsert them later on, e.g.:
Extract
ffmpeg -f lavfi -i "movie=cc.mp4[out0+subcc]" -map s cc.srt
, reinsert
ffmpeg  -f lavfi -i testsrc=duration=20:size=1920x1080:rate=30 -i cc.srt  -c:v libx264 -c:s mov_text -metadata:s:s:0 language=eng mix.mp4
and confirm
ffprobe -v error -show_entries stream=index,codec_name,codec_type mix.mp4 
[STREAM]
index=0
codec_name=h264
codec_type=video
[/STREAM]
[STREAM]
index=1
codec_name=mov_text
codec_type=subtitle
[/STREAM]

Hope this helps.
Cheers,

**Comment by scottf-tvw** [comment]
This I have to say, in untechnical terms is pretty lame.. is this on the roadmap at all?
Thanks for the noted option but this is to insert subtitles not captions. This is why EIA-608/EIA-708 needs to be retained for our clients. At this point we cannot continue evaluating this option for our platform.

**Comment by NastoohX** [comment]
Hi,
For roadmap related questions, kindly, contact Video-SDK@amd.com.
Cheers,
