### ISSUE TITLE
Lookahead depth of 20 can fail - improved guidance in documentation needed

### ISSUE THREAD

**Issue by shaunclimbon** [Xilinx/video-sdk#64]
20 is the maximum depth that can be handled for 60fps inputs.  But if 30fps inputs are used at full density OOM errors can occur.  Better guidance would be to recommend 1/3 the frame rate as a starting point with the maximum value being application dependent.

**Comment by NastoohX** [comment]
Hi,
Thank you for your comment. Your feedback will be taken into account for future releases.
Cheers,

**Comment by NastoohX** [comment]
Hi,
The request has been integrated into our latest documentation.
Cheers,
