### ISSUE TITLE
Video SDK version 3.0 now available

### ISSUE THREAD

**Issue by ThomasXilinx** [Xilinx/video-sdk#68]
**Version 3.0 of the Video SDK is now officially released.** 

Some of the new features in this release include:
- Support for deployment and installation through package feed
- Dynamic GOP
- Ultra low latency (ULL) encoding
- Min/max frame QP bounding
- Enhanced operating system support

Please refer to the documentation for additional details:
https://xilinx.github.io/video-sdk/v3.0/release_notes.html

Note that Amazon EC2 VT1 instances have not yet been upgraded to support this new version, Support for version 3.0 of the Xilinx Video SDK on Amazon EC2 VT1 is expected soon. Until then, version 2.0 or 2.0.1 of the Video SDK should be used on VT1 instances.

**Comment by Batuzz** [comment]
Hello,
are there any plans to support new FFMPEG versions? eg. 5.1 LTS or 6.0+?

Kind regards,
Bartosz

**Comment by Mudpuppy12** [comment]
Any updates for the update EC2 VT1 instances? It's been about 30 days.

**Comment by Qizot** [comment]
AMI with version 3.0 is already available.

**Comment by ThomasXilinx** [comment]
VT1 instances are now indeed available with v3.0:
https://xilinx.github.io/video-sdk/v3.0/getting_started_on_vt1.html

AMIs with v3.0 are also available:
https://aws.amazon.com/marketplace/search/results?searchTerms=VT1&sort=LAST_MODIFIED_TIME-DESCENDING&CREATOR=c68d4b68-cde0-47b8-bc40-a1c2886ca280&filters=CREATOR

**Comment by duthv-amd** [comment]
Closing this issue as it is not a real issue, rather an announcement.  Moved this to: 
https://github.com/Xilinx/video-sdk/discussions/81
