### ISSUE TITLE
[AWS VT1] Unable to run the "13_ffmpeg_transcode_only_split_stitch.py" example script

### ISSUE THREAD

**Issue by gdufourcq** [Xilinx/video-sdk#7]
Hi,
I was able to successfully run the script "11_ffmpeg_ftrt_transcode_only.sh" with Big Buck Bunny file.
However, I faced issues with the "13_ffmpeg_transcode_only_split_stitch.py" with the same file and other ones:

![error1](https://user-images.githubusercontent.com/30148903/138096750-a2a0c674-501c-4101-bf7f-79392239415a.png)

![error2](https://user-images.githubusercontent.com/30148903/138096778-c04f58f9-91ca-413b-b938-1a3adbf1ba45.png)

Can you provide detailled information about the input file requierements?
Can you provide a sample input file that you know will work with this script?

Thanks

**Comment by ThomasXilinx** [comment]
The "13_ffmpeg_transcode_only_split_stitch.py" script has been updated in the newly released v2.0 of the SDK.
