### ISSUE TITLE
Path in Dockerfile KO

### ISSUE THREAD

**Issue by gmarchand** [Xilinx/video-sdk#70]
The path of this command line is not good : https://github.com/Xilinx/video-sdk/blob/v2.0/dockerfiles/vt1/Dockerfile.ubuntu20.04_sw#L44

The good command line : `RUN cd /usr/src/build/release/U30_Ubuntu_20.04_v2.0.1; ./install -sw`

**Comment by NastoohX** [comment]
Thank you for bringing this to our attention. The respectively dockerfiles will be updated.
Cheers,
