### ISSUE TITLE
Decode 1080p@5fps

### ISSUE THREAD

**Issue by kevinzezel** [Xilinx/video-sdk#72]
Hi,

I saw in the documentation that each Alveo U30 card can decode 16 streams at 1080p@30fps. If I lower the frame rate of the RTSP cameras to 5 FPS, can I increase the amount of stream per camera?

Is it correct to say:
16x 1080p@30fps
96x 1080p@5fps

How can I monitor card usage? Similar to htop for CPU and nvtop for GPU.

Regards,
Kevin

**Comment by NastoohX** [comment]
Hi,
Thank you for your question. Although, the card allows for linear increase in density, as an inverse function of FPS; however, at higher densities, other factors including PCIe traffic and control software overhead may show a diminishing return. You need to test for a stable density, in your specific use case. We report on typical use-cases here: https://xilinx.github.io/video-sdk/v3.0/specs_and_features.html#performance-tables.
To get performance numbers out of U30, use  `xrmadm /opt/xilinx/xrm/test/list_cmd.json` command. For example if you were to decode a 4kp60 content, the decoder should report full utilisation:
"cu_3": {
                    "cuId         ": "3",
                    "cuType       ": "IP Kernel",
                    "kernelName   ": "decoder",
                    "kernelAlias  ": "DECODER_MPSOC",
                    "instanceName ": "decoder_1",
                    "cuName       ": "decoder:decoder_1",
                    "kernelPlugin ": "/opt/xilinx/xma_plugins/libvcu-xma-dec-plg.so",
                    "maxCapacity  ": "497664000",
                    "numChanInuse ": "1",
                    "usedLoad     ": "1000000 of 1000000",
},
, whereas, if you were to decode a 4kp5 content, it will report 1/12th of utilisation:
 "cu_3": {
                    "cuId         ": "3",
                    "cuType       ": "IP Kernel",
                    "kernelName   ": "decoder",
                    "kernelAlias  ": "DECODER_MPSOC",
                    "instanceName ": "decoder_1",
                    "cuName       ": "decoder:decoder_1",
                    "kernelPlugin ": "/opt/xilinx/xma_plugins/libvcu-xma-dec-plg.so",
                    "maxCapacity  ": "497664000",
                    "numChanInuse ": "1",
                    "usedLoad     ": "83333 of 1000000",
},
Hope this helps.
Cheers,

**Comment by kevinzezel** [comment]
Thank you!!

**Comment by NastoohX** [comment]
Great. 
I'll close this ticket for now, but feel free to reopen it or issue a new one.
Cheers,
