### ISSUE TITLE
Yum update on IMAGE_ID="ami-085c834167fc3623c

### ISSUE THREAD

**Issue by Mudpuppy12** [Xilinx/video-sdk#75]
Having trouble with yum update with the latest 3.0 image.  What would be the right work around?

[root@ip-10-0-0-214 ~]# yum update
Loaded plugins: dkms-build-requires, extras_suggestions, langpacks, priorities, update-motd
Repository Amzn2Artifactory is listed more than once in the configuration
Repository Artifactory is listed more than once in the configuration
Repository BaseArtifactory is listed more than once in the configuration
224 packages excluded due to repository priority protections
Resolving Dependencies
[plugin/dkms-build-requires]: Found kernels in transaction, adding corresponding devel and gcc package(s)
--> Running transaction check
---> Package ca-certificates.noarch 0:2021.2.50-72.amzn2.0.5 will be updated
---> Package ca-certificates.noarch 0:2021.2.50-72.amzn2.0.7 will be an update
---> Package cloud-init.noarch 0:19.3-46.amzn2 will be updated
---> Package cloud-init.noarch 0:19.3-46.amzn2.0.1 will be an update
---> Package curl.x86_64 0:7.88.1-1.amzn2.0.1 will be updated
---> Package curl.x86_64 0:8.0.1-1.amzn2.0.1 will be an update
---> Package dbus.x86_64 1:1.10.24-7.amzn2.0.2 will be updated
---> Package dbus.x86_64 1:1.10.24-7.amzn2.0.3 will be an update
---> Package dbus-libs.x86_64 1:1.10.24-7.amzn2.0.2 will be updated
---> Package dbus-libs.x86_64 1:1.10.24-7.amzn2.0.3 will be an update
---> Package fribidi.x86_64 0:1.0.2-1.amzn2.1 will be updated
---> Package fribidi.x86_64 0:1.0.2-1.amzn2.1.1 will be an update
---> Package fribidi-devel.x86_64 0:1.0.2-1.amzn2.1 will be updated
---> Package fribidi-devel.x86_64 0:1.0.2-1.amzn2.1.1 will be an update
---> Package git.x86_64 0:2.39.2-1.amzn2.0.1 will be updated
---> Package git.x86_64 0:2.40.1-1.amzn2.0.1 will be an update
---> Package git-core.x86_64 0:2.39.2-1.amzn2.0.1 will be updated
---> Package git-core.x86_64 0:2.40.1-1.amzn2.0.1 will be an update
---> Package git-core-doc.noarch 0:2.39.2-1.amzn2.0.1 will be updated
---> Package git-core-doc.noarch 0:2.40.1-1.amzn2.0.1 will be an update
---> Package glibc.x86_64 0:2.26-62.amzn2 will be updated
---> Package glibc.x86_64 0:2.26-63.amzn2 will be an update
---> Package glibc-all-langpacks.x86_64 0:2.26-62.amzn2 will be updated
---> Package glibc-all-langpacks.x86_64 0:2.26-63.amzn2 will be an update
---> Package glibc-common.x86_64 0:2.26-62.amzn2 will be updated
---> Package glibc-common.x86_64 0:2.26-63.amzn2 will be an update
---> Package glibc-devel.x86_64 0:2.26-62.amzn2 will be updated
---> Package glibc-devel.x86_64 0:2.26-63.amzn2 will be an update
---> Package glibc-headers.x86_64 0:2.26-62.amzn2 will be updated
---> Package glibc-headers.x86_64 0:2.26-63.amzn2 will be an update
---> Package glibc-locale-source.x86_64 0:2.26-62.amzn2 will be updated
---> Package glibc-locale-source.x86_64 0:2.26-63.amzn2 will be an update
---> Package glibc-minimal-langpack.x86_64 0:2.26-62.amzn2 will be updated
---> Package glibc-minimal-langpack.x86_64 0:2.26-63.amzn2 will be an update
---> Package grub2.x86_64 1:2.06-9.amzn2.0.1 will be obsoleted
---> Package grub2.x86_64 1:2.06-9.amzn2.0.3 will be obsoleting
---> Package grub2-common.noarch 1:2.06-9.amzn2.0.1 will be updated
---> Package grub2-common.noarch 1:2.06-9.amzn2.0.3 will be an update
---> Package grub2-efi-x64-ec2.x86_64 1:2.06-9.amzn2.0.1 will be updated
---> Package grub2-efi-x64-ec2.x86_64 1:2.06-9.amzn2.0.3 will be an update
---> Package grub2-pc.x86_64 1:2.06-9.amzn2.0.1 will be updated
---> Package grub2-pc.x86_64 1:2.06-9.amzn2.0.3 will be obsoleting
---> Package grub2-pc-modules.noarch 1:2.06-9.amzn2.0.1 will be updated
---> Package grub2-pc-modules.noarch 1:2.06-9.amzn2.0.3 will be an update
---> Package grub2-tools.x86_64 1:2.06-9.amzn2.0.1 will be obsoleted
---> Package grub2-tools.x86_64 1:2.06-9.amzn2.0.3 will be obsoleting
---> Package grub2-tools-efi.x86_64 1:2.06-9.amzn2.0.3 will be obsoleting
---> Package grub2-tools-extra.x86_64 1:2.06-9.amzn2.0.3 will be obsoleting
---> Package grub2-tools-minimal.x86_64 1:2.06-9.amzn2.0.1 will be updated
---> Package grub2-tools-minimal.x86_64 1:2.06-9.amzn2.0.3 will be obsoleting
---> Package hibagent.noarch 0:1.1.0-5.amzn2 will be updated
---> Package hibagent.noarch 0:1.1.0-6.amzn2 will be an update
---> Package kernel.x86_64 0:5.10.179-171.711.amzn2 will be installed
---> Package kpatch-runtime.noarch 0:0.9.4-6.amzn2 will be updated
---> Package kpatch-runtime.noarch 0:0.9.4-8.amzn2 will be an update
---> Package libcrypt.x86_64 0:2.26-62.amzn2 will be updated
---> Package libcrypt.x86_64 0:2.26-63.amzn2 will be an update
---> Package libcurl.x86_64 0:7.88.1-1.amzn2.0.1 will be updated
---> Package libcurl.x86_64 0:8.0.1-1.amzn2.0.1 will be an update
---> Package libfastjson.x86_64 0:0.99.4-3.amzn2 will be updated
---> Package libfastjson.x86_64 0:0.99.4-3.amzn2.0.1 will be an update
---> Package libssh2.x86_64 0:1.4.3-12.amzn2.2.3 will be updated
---> Package libssh2.x86_64 0:1.4.3-12.amzn2.2.4 will be an update
---> Package libtiff.x86_64 0:4.0.3-35.amzn2.0.5 will be updated
---> Package libtiff.x86_64 0:4.0.3-35.amzn2.0.6 will be an update
---> Package libwebp.x86_64 0:0.3.0-10.amzn2 will be updated
---> Package libwebp.x86_64 0:0.3.0-10.amzn2.0.2 will be an update
---> Package libxml2.x86_64 0:2.9.1-6.amzn2.5.6 will be updated
---> Package libxml2.x86_64 0:2.9.1-6.amzn2.5.8 will be an update
---> Package libxml2-python.x86_64 0:2.9.1-6.amzn2.5.6 will be updated
---> Package libxml2-python.x86_64 0:2.9.1-6.amzn2.5.8 will be an update
---> Package mariadb-libs.x86_64 1:5.5.68-1.amzn2 will be updated
---> Package mariadb-libs.x86_64 1:5.5.68-1.amzn2.0.1 will be an update
---> Package microcode_ctl.x86_64 2:2.1-47.amzn2.0.14 will be updated
---> Package microcode_ctl.x86_64 2:2.1-47.amzn2.0.15 will be an update
---> Package mtr.x86_64 2:0.92-2.amzn2 will be updated
---> Package mtr.x86_64 2:0.92-2.amzn2.0.1 will be an update
---> Package net-tools.x86_64 0:2.0-0.22.20131004git.amzn2.0.2 will be updated
---> Package net-tools.x86_64 0:2.0-0.22.20131004git.amzn2.0.3 will be an update
---> Package openssh.x86_64 0:7.4p1-22.amzn2.0.1 will be updated
---> Package openssh.x86_64 0:7.4p1-22.amzn2.0.2 will be an update
---> Package openssh-clients.x86_64 0:7.4p1-22.amzn2.0.1 will be updated
---> Package openssh-clients.x86_64 0:7.4p1-22.amzn2.0.2 will be an update
---> Package openssh-server.x86_64 0:7.4p1-22.amzn2.0.1 will be updated
---> Package openssh-server.x86_64 0:7.4p1-22.amzn2.0.2 will be an update
---> Package openssl.x86_64 1:1.0.2k-24.amzn2.0.6 will be updated
---> Package openssl.x86_64 1:1.0.2k-24.amzn2.0.7 will be an update
---> Package openssl-devel.x86_64 1:1.0.2k-24.amzn2.0.6 will be updated
---> Package openssl-devel.x86_64 1:1.0.2k-24.amzn2.0.7 will be an update
---> Package openssl-libs.x86_64 1:1.0.2k-24.amzn2.0.6 will be updated
---> Package openssl-libs.x86_64 1:1.0.2k-24.amzn2.0.7 will be an update
---> Package pcre.x86_64 0:8.32-17.amzn2.0.2 will be updated
---> Package pcre.x86_64 0:8.32-17.amzn2.0.3 will be an update
---> Package pcre-devel.x86_64 0:8.32-17.amzn2.0.2 will be updated
---> Package pcre-devel.x86_64 0:8.32-17.amzn2.0.3 will be an update
---> Package perl-Git.noarch 0:2.39.2-1.amzn2.0.1 will be updated
---> Package perl-Git.noarch 0:2.40.1-1.amzn2.0.1 will be an update
---> Package python-babel.noarch 0:0.9.6-8.amzn2.0.1 will be updated
---> Package python-babel.noarch 0:0.9.6-8.amzn2.0.2 will be an update
---> Package python2-rpm.x86_64 0:4.11.3-48.amzn2.0.2 will be updated
---> Package python2-rpm.x86_64 0:4.11.3-48.amzn2.0.3 will be an update
---> Package python3.x86_64 0:3.7.16-1.amzn2.0.1 will be updated
---> Package python3.x86_64 0:3.7.16-1.amzn2.0.2 will be an update
---> Package python3-libs.x86_64 0:3.7.16-1.amzn2.0.1 will be updated
---> Package python3-libs.x86_64 0:3.7.16-1.amzn2.0.2 will be an update
---> Package rpm.x86_64 0:4.11.3-48.amzn2.0.2 will be updated
---> Package rpm.x86_64 0:4.11.3-48.amzn2.0.3 will be an update
---> Package rpm-build-libs.x86_64 0:4.11.3-48.amzn2.0.2 will be updated
---> Package rpm-build-libs.x86_64 0:4.11.3-48.amzn2.0.3 will be an update
---> Package rpm-libs.x86_64 0:4.11.3-48.amzn2.0.2 will be updated
---> Package rpm-libs.x86_64 0:4.11.3-48.amzn2.0.3 will be an update
---> Package rpm-plugin-systemd-inhibit.x86_64 0:4.11.3-48.amzn2.0.2 will be updated
---> Package rpm-plugin-systemd-inhibit.x86_64 0:4.11.3-48.amzn2.0.3 will be an update
---> Package rsync.x86_64 0:3.1.2-11.amzn2.0.1 will be updated
---> Package rsync.x86_64 0:3.1.2-11.amzn2.0.2 will be an update
---> Package screen.x86_64 0:4.1.0-0.27.20120314git3c2946.amzn2 will be updated
---> Package screen.x86_64 0:4.1.0-0.27.20120314git3c2946.amzn2.0.1 will be an update
---> Package tar.x86_64 2:1.26-35.amzn2.0.1 will be updated
---> Package tar.x86_64 2:1.26-35.amzn2.0.2 will be an update
---> Package tzdata.noarch 0:2022g-1.amzn2.0.2 will be updated
---> Package tzdata.noarch 0:2023c-1.amzn2.0.1 will be an update
---> Package xrt.x86_64 0:2.11.722-1 will be updated
--> Processing Dependency: xrt = 2.11.722 for package: xilinx-alveo-u30-core-3.0.1-1.x86_64
---> Package xrt.x86_64 0:2.15.230-1 will be an update
--> Finished Dependency Resolution
--> Running transaction check
---> Package kernel.x86_64 0:5.4.226-129.415.amzn2 will be erased
---> Package xrt.x86_64 0:2.11.722-1 will be updated
--> Processing Dependency: xrt = 2.11.722 for package: xilinx-alveo-u30-core-3.0.1-1.x86_64
--> Finished Dependency Resolution
Error: Package: xilinx-alveo-u30-core-3.0.1-1.x86_64 (@Amzn2Artifactory)
           Requires: xrt = 2.11.722
           Removing: xrt-2.11.722-1.x86_64 (@Amzn2Artifactory)
               xrt = 2.11.722-1
           Updated By: xrt-2.15.230-1.x86_64 (Amzn2Artifactory)
               xrt = 2.15.230-1
           Available: xrt-2.11.716-1.x86_64 (Amzn2Artifactory)
               xrt = 2.11.716-1
           Available: xrt-2.14.354-1.x86_64 (Amzn2Artifactory)
               xrt = 2.14.354-1
           Available: xrt-2.14.367-1.x86_64 (Amzn2Artifactory)
               xrt = 2.14.367-1
           Available: xrt-2.14.384-1.x86_64 (Amzn2Artifactory)
               xrt = 2.14.384-1
           Available: xrt-2.14.413-1.x86_64 (Amzn2Artifactory)
               xrt = 2.14.413-1
           Available: xrt-2.15.225-1.x86_64 (Amzn2Artifactory)
               xrt = 2.15.225-1
           Available: xrt-2.15.228-1.x86_64 (Amzn2Artifactory)
               xrt = 2.15.228-1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Installed Packages
Name        : xrt
Arch        : x86_64
Version     : 2.11.722
Release     : 1
Size        : 44 M
Repo        : installed
From repo   : Amzn2Artifactory
Summary     : Xilinx RunTime stack for use with Xilinx FPGA platforms
License     : unknown
Description : DESCRIPTION
            : ===========
            :
            : This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.

Available Packages
Name        : xrt
Arch        : x86_64
Version     : 2.15.230
Release     : 1
Size        : 10 M
Repo        : Amzn2Artifactory
Summary     : Xilinx RunTime stack for use with Xilinx FPGA platforms
License     : unknown
Description : DESCRIPTION
            : ===========
            : This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.

[ec2-user@ip-10-0-0-214 ~]$ xbutil examine
System Configuration
  OS Name              : Linux
  Release              : 5.10.167-147.601.amzn2.x86_64
  Version              : #1 SMP Tue Feb 14 21:50:23 UTC 2023
  Machine              : x86_64
  CPU Cores            : 12
  Memory               : 22526 MB
  Distribution         : Amazon Linux 2
  GLIBC                : 2.26
  Model                : vt1.3xlarge

XRT
  Version              : 2.11.722
  Branch               : 2021.1
  Hash                 : d1ecc641da7b8805e778926e3354e8dd3fdaa6a8
  Hash Date            : 2023-01-25 23:37:46
  XOCL                 : 2.11.722, d1ecc641da7b8805e778926e3354e8dd3fdaa6a8
  XCLMGMT              : unknown, unknown

Devices present
  [0000:00:1f.0] : xilinx_u30_gen3x4_base_2
  [0000:00:1e.0] : xilinx_u30_gen3x4_base_2

**Comment by NastoohX** [comment]
Hi,
Seems that xrt version was not locked to 2.11.722. Proceed by removing all existing SDK packages, yum update, locking xrt version and final installing SDK packages, as per https://xilinx.github.io/video-sdk/v3.0/getting_started_on_prem.html#install-the-sdk. Let us know if this resolves your issue.
Cheers,

**Comment by Mudpuppy12** [comment]
Thank you, to resolve I did the following:

# yum install yum-plugin-versionlock
# yum versionlock xrt-2.11.722


That did the trick.
