### ISSUE TITLE
OS journald configuration can lead to incorrect latency logging measurements

### ISSUE THREAD

**Issue by shaunclimbon** [Xilinx/video-sdk#82]
The "-latency_logging" option relies on journald logs but if journald is not configured in a specific manner the latency reporting will be incorrect.  Documentation should be updated to indicate the required configuration.  For example, on one particular system the following changes were needed to /etc/systemd/journald.conf

RateLimitInterval=0
RateLimitBurst=0

This disables rate control of journal messages.

**Comment by NastoohX** [comment]
Hi,
Thank you for your input. Journal configuration has been added to the SDK documentation.
Cheers,
