### ISSUE TITLE
Accurate seeking in video

### ISSUE THREAD

**Issue by balaprassanna** [Xilinx/video-sdk#96]
I'm working on a custom video processing workflow where I need to split and transcode large video files into 15-minute chunks using Xilinx's video SDK on U30 and MA35D. I've been trying to use the -ss and -to options in FFmpeg as mentioned in this [link](https://trac.ffmpeg.org/wiki/Seeking), but I'm encountering accuracy issues due to keyframe-based seeking. I know that FFmpeg with libx264 provides frame-accurate seeking during transcoding even when used as input parameter.

Is there a way to achieve similar frame-accurate seeking using Xilinx's video SDK on U30 and MA35D? If so, could you please provide specific instructions or examples?

**Comment by NastoohX** [comment]
Hi,
Thank you for bring this issue to our attention. I'll raise the issue with our dev team, and if there are specific hooks, they'll be noted here. Meanwhile, would using "-ss" after specifying the input give the required accuracy?
Cheers,

**Comment by balaprassanna** [comment]
Hi,
Thanks for looking into this. Specifying -ss after the input results in slow processing, especially for large video files. According to the FFmpeg wiki [link](https://trac.ffmpeg.org/wiki/Seeking), using -ss after the input causes FFmpeg to transcode the video from the beginning up to the seek position, rather than performing a keyframe-based seek. This leads to the slower processing.

**Comment by NastoohX** [comment]
Hi,
The feedback provided from R&D, indicates that our SDK does not offer accelerated parsing for fast skipping.
Cheers,

**Comment by bhargav-sudo** [comment]
Hi,

Can we expect this support in future SDK release atleast with MA35D ?
